.github/workflows/codeql-analysis.yml
* is a special character in YAML, so we must use quotes
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
=> fix(codeql): fix branch wildcard

.github/workflows/depsreview.yml
> This action scans your pull requests for dependency changes and will raise an error if any
> new dependencies have existing vulnerabilities. The action is supported
> by an API endpoint that diffs the dependencies between any two revisions.
- Included the https://github.com/actions/dependency-review-action
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Included dependency review check

pkg/provenance.go
Allow slsa-verifier to verify provenance from the slsa-github-generator workflow.
https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/slsa2_provenance.yml
=> Add provenance only workflow

pkg/provenance.go
The Go builders have been migrated into https://github.com/slsa-framework/slsa-github-generator, so we need to add them to the list of trusted builders.
Note: We'll remove the other ones before the v1 release
=> ✨ Add trusted builder

README.md, main.go, pkg/provenance.go
Some output and error statements were printed and prevented someone from piping output to `jq` or other programs.
=> bug: fix prints to stdout and stderr and update README.md

README.md, SHA256SUM.md
This file updates documentation for slsa-verifier releaes v1.0.0
https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.0.0
To verify the release, 
1. Download the binary [slsa-verifier-linux-amd64](https://github.com/slsa-framework/slsa-verifier/releases/download/v1.0.0/slsa-verifier-linux-amd64) and provenance [slsa-verifier-linux-amd64.intoto.jsonl](https://github.com/slsa-framework/slsa-verifier/releases/download/v1.0.0/slsa-verifier-linux-amd64.intoto.jsonl) from [Assets](https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.0.0)
2. Close this repository, and run the verifier
```
$ go run . -artifact-path slsa-verifier-linux-amd64 -provenance …
```
=> release: Release v1.0.0! Update documentation

README.md, main.go, main_test.go, pkg/provenance.go
see title
Fixes https://github.com/slsa-framework/slsa-verifier/issues/86
Also prints the Rekor URL of the verified entry. this was some feedback given by Brandon earlier. 
=> feat: add an option to print provenance

README.md, SHA256SUM.md
This sets the expected sha256 of the v1.1.0 slsa-verifier released binary.
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.1.0
```
$ (Optional: git checkout v1.1.0)
$ go run . -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.1.0
```
Either:
```
cat slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.payload' | base64 -d | jq -r '.subject[0].digest.sha256'
```
or
```
sha256sum slsa-verifier-linux-amd64
```
=> release: update to release 1.1.0

pkg/provenance.go, pkg/rekor.go
When seeing rekor entry errors, we only see `could not find a matching valid signature entry`. this augments the error messages with any unexpected errors.
=> debug: add error messages for debugging with rekor

README.md, main.go, pkg/rekor.go
Fixes https://github.com/slsa-framework/slsa-verifier/issues/156
Updates README.md with the new output.
=> fix: remove signing certificate output

README.md, RELEASE.md, SHA256SUM.md
This sets the expected sha256 of the v1.2.0 slsa-verifier released binary.
How to LGTM this PR (I'll work on a proper doc for this in https://github.com/slsa-framework/slsa-github-generator/issues/112):
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.2.0
```
$ (Optional: git checkout tags/v1.2.0)
$ go run . -provenance ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl -artifact-path ~/Downloads/slsa-verifier-linux-amd64 -source github.com/slsa-framework/slsa-verifier -tag v1.2.0
```
Either:
```
cat …
```
=> release: add notes for release v1.2.0

README.md, RELEASE.md
- update link to download the binary to use the latest release (v1.2.0)
=> update link to download the binary to use the latest release (v1.2.0)

README.md, RELEASE.md, SHA256SUM.md
This sets the expected sha256 of the v1.3.0 slsa-verifier released binary.
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.0
```
$ (Optional: git checkout tags/v1.3.0)
$ go run ./cli/slsa-verifier -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.3.0
```
Either:
```
cat slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.payload' | base64 -d | jq -r '.subject[0].digest.sha256'
```
or
```
sha256sum slsa-verifier-linux-amd64
```
The …
=> release: release v1.3.0 of verifier

SHA256SUM.md
This sets the expected sha256 of the v1.0.3 slsa-verifier released binary.
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.0.3
```
$ (Optional: git checkout tags/v1.0.3)
$ go run ./cli/slsa-verifier -artifact-path slsa-verifier-linux-amd64 -provenance slsa-verifier-linux-amd64.intoto.jsonl -source github.com/slsa-framework/slsa-verifier -tag v1.0.3
```
Either:
```
cat slsa-verifier-linux-amd64.intoto.jsonl | jq -r '.payload' | base64 -d | jq -r '.subject[0].digest.sha256'
```
or
```
sha256sum slsa-verifier-linux-amd64
```
The output hash should be the hash I'm updating …
=> release: add release v1.0.3

errors/errors.go, go.mod, go.sum, verifiers/internal/gcb/provenance.go, verifiers/internal/gcb/provenance_test.go, verifiers/internal/gcb/verifier.go
GCB has an additional text human-readable version of the DSSE payload. This PR verifiers that it matches the verified DSSE payload.
=> Verify text provenance for GCB

cli/slsa-verifier/verify.go
This is causing e2e failures:
c/f https://github.com/slsa-framework/example-package/runs/8226006614?check_suite_focus=true#step:6:196
https://github.com/slsa-framework/slsa-github-generator/issues/821
=> fix: fix CLI flag mishap

verifiers/internal/gha/rekor.go
Makes client aware of shards when verifying the root hash.
The root (!) cause of the issue with the backports is that we were attempting to verify consistency with a signed tree head with the root hash received in the inclusion proof (unsigned).
Requesting the current tree head was the current ACTIVE shard, NOT the shard the entry was on.
Now, we search the inactive shards too in case one of those matches the tree ID of the entry.
=> fix: make client shard aware when verifying

main_test.go, pkg/provenance.go
Backport shard-aware fix to v1.1: allows searching through inactive shard's STHs. when verifying entries consistency with an STH.
=> fix(backport/v1.1): make client shard aware when verifying entries on inactive shards

README.md, RELEASE.md, SHA256SUM.md
Waiting on https://github.com/slsa-framework/slsa-verifier/pull/287 for release/v1.1 branch.
To verify these hashes, do the following for https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.1 and https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.2.1
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.1 (or the other)
```
$  go run ./cli/slsa-verifier verify-artifact ~/Downloads/slsa-verifier-linux-amd64 --provenance-path ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl --source-uri …
```
=> release: add release v1.3.1 and v1.2.1

SHA256SUM.md
To verify these hashes, do the following for https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.1.2 and  https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.0.4
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.1.2 (or the other)
```
$  go run ./cli/slsa-verifier verify-artifact ~/Downloads/slsa-verifier-linux-amd64 --provenance-path ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl --source-uri github.com/slsa-framework/slsa-verifier --source-tag v1.1.2 --source-branch release/v1.1
```
Either:
```
cat …
```
=> release: add release hash for v1.1.2 and v1.0.4

cli/slsa-verifier/main_test.go, cli/slsa-verifier/testdata/gcb_container/v0.3/gcloud-container-gcs.json, cli/slsa-verifier/testdata/gcb_container/v0.3/gcloud-container-gcs/index.json, verifiers/internal/gcb/intoto.go, verifiers/internal/gcb/provenance.go, verifiers/internal/gcb/provenance_test.go, verifiers/internal/gcb/testdata/gcloud-container-gcs.json
This PR does two things in order to achieve GCB provenance compatibility:
1. Adds support for incorrect string/int JSON for intoto. I temporarily vendor the GCB provenance and omit the `definedInMaterial` field. Until GCB updates their provenance generation, this will have to do.
2. Also adds support for GCS versioned buckets. I spoke with the GCB team: `v0.3` does not necessarily produce level 3 provenance, and we can only guarantee the provenance requirements (up to non-falsifiability for v0.3). We should definitely prioritize a versioning option in the future that would disallow generating provenance in a lower level mannger.
Adds testcase for the JSON marshalling issue and the GCS Buckets.
=> gcb: add gcb compatibility for provenance formats and buckets

.github/config-release.yml
Tested with the build-dry command, before and after.
```
asraa@asraa1:~/git/slsa-verifier$  ~/Downloads/slsa-builder-go-linux-amd64  build --dry .github/config-release.yml VERSION:
&{linux amd64 <nil> 0xc0005880f0 map[CGO_ENABLED:0 GO111MODULE:on] [-trimpath -tags=netgo] [-X sigs.k8s.io/release-utils/version.gitVersion={{ .Env.Version }}] slsa-verifier-{{ .Os }}-{{ .Arch }}}
&{linux amd64 <nil> 0xc000155700 map[CGO_ENABLED:0 GO111MODULE:on] [-trimpath -tags=netgo] [-X sigs.k8s.io/release-utils/version.gitVersion={{ .Env.Version }}] slsa-verifier-{{ .Os }}-{{ .Arch }}}
arg env: VERSION:
env variable empty or not set: {{ .Env.Version }}bash: syntax error near unexpected token `&'
asraa@asraa1:~/git/slsa-verifier$ …
```
=> fix: env vars are case sensitive in configuration

RELEASE.md
Fixes https://github.com/slsa-framework/slsa-verifier/issues/299
* Updates release process to include a pre-release step that ensures that the final release has verified provenance and is verified with the e2e tests
=> docs: update release.md docs to describe a pre-release

README.md, cli/slsa-verifier/verify/options.go
This adds missing [optional] annotations to flags in the verify-artifact --help message.
Alternatively, we could just indicate what flags are [required] - there are only two of them - and remove all the [optional] noise from all other flags.
=> Add optional

actions/installer/action.yml
=> Make GitHub token optional

.github/workflows/release.yml
The update to builder v1.2.1 requires an update in the permissions (to detect the env)
=> release/v1.0: fix release workflow permissions

README.md, SHA256SUM.md
To verify these hashes, do the following for https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.2, https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.2.2, https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.1.3, https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.0.5
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v1.3.2 (or the other)
```
$  go run ./cli/slsa-verifier verify-artifact ~/Downloads/slsa-verifier-linux-amd64 --provenance-path ~/Downloads/slsa-verifier-linux-amd64.intoto.jsonl …
```
=> releases: add new releases to SHA256SUM.md

verifiers/internal/gha/rekor.go
Fix error logs.
I guess these codes are copied from the just before error handling mistakenly.
https://github.com/slsa-framework/slsa-verifier/blob/137528a257f4533d7445ec6ae1bc57011784dab0/verifiers/internal/gha/rekor.go#L81
=> fix: fix error logs

cli/experimental/service/main.go, cli/slsa-verifier/main_test.go, cli/slsa-verifier/verify.go, cli/slsa-verifier/verify/options.go, cli/slsa-verifier/verify/verify_artifact.go, cli/slsa-verifier/verify/verify_image.go, experimental/rest/service.go, go.mod, register/register.go, verifiers/internal/gcb/keys/keys.go, verifiers/internal/gcb/provenance.go, verifiers/internal/gcb/provenance_test.go, verifiers/internal/gcb/verifier.go, verifiers/internal/gha/builder.go, verifiers/internal/gha/builder_test.go, verifiers/internal/gha/provenance.go, verifiers/internal/gha/provenance_test.go, verifiers/internal/gha/rekor.go, verifiers/internal/gha/rekor_test.go, verifiers/internal/gha/verifier.go, verifiers/utils/builder.go, verifiers/utils/builder_test.go, verifiers/utils/container/container.go, verifiers/verifier.go
Fix the package name `github.com/slsa-framework/slsa-verifier` to `github.com/slsa-framework/slsa-verifier/v2`.
```sh
git ls-files | grep ".go$" | xargs -n 1 gsed -i "s|github.com/slsa-framework/slsa-verifier|github.com/slsa-framework/slsa-verifier/v2|g"
```
slsa-verifier v2 has been released. https://github.com/slsa-framework/slsa-verifier/releases/tag/v2.0.0
Currently, we can't install slsa-verifier v2 by `go install`.
1. Failed to install v2.
```console
$ go install github.com/slsa-framework/slsa-verifier/cli/slsa-verifier@v2.0.0
go: github.com/slsa-framework/slsa-verifier/cli/slsa-verifier@v2.0.0: github.com/slsa-framework/slsa-verifier@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/slsa-framework/slsa-verifier/v2")
```
2. …
=> fix: fix the Go package version to v2

README.md
Depends on https://github.com/slsa-framework/slsa-verifier/pull/373
=> docs: refer v2.0.0 in README

README.md
https://github.com/slsa-framework/slsa-verifier/pull/375#discussion_r1037775148
I found this doesn't work.
To install slsa-verifier v2 by go install, we have to release v2.0.1 or later.
```console
$ go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.0.0
go: github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.0.0: github.com/slsa-framework/slsa-verifier@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/slsa-framework/slsa-verifier/v2")
```
So I revert this change.
When we'll release v2.0.1, we would be able to install slsa-verifier v2 by go install.
```console
$ go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.0.1
```
Signed-off-by: Shunsuke Suzuki …
=> docs: fix go install

cli/slsa-verifier/main_test.go, cli/slsa-verifier/verify/options.go
bug fix: this fixes a nil map entry assignment when creating workflow input flags.
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/1299
=> fix: handle workflow input flag parsing

verifiers/internal/gcb/provenance.go
closes https://github.com/slsa-framework/slsa-verifier/issues/377
We perform both std and URL base64 decoding, so adding a comment why.
=> docs: Add comment for signature decoding

verifiers/internal/gcb/provenance.go
Updates #377 
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>
=> fix: Fix error check for decodeSignature

.github/workflows/schedule.installer.yml
This allows us to run the workflow manually to test a list of versions.
=> feat: allow version to be empty for Installer tests

.github/workflows/schedule.installer.yml, .github/workflows/scripts/schedule.actions/verifier-installer.sh
Signed-off-by: laurentsimon <laurentsimon@google.com>
closes https://github.com/slsa-framework/slsa-verifier/issues/405
=> fix: token permission in Installer scheduled tests

cli/slsa-verifier/verify.go
One part that is missing in the output if invocation is wrong is that there is no indication that user has to pass path to a file (artifact/image).
The remaining potential errors from #173 are handled via #231.
Found while looking at #174.
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
=> feat: Enhance help message

cli/slsa-verifier/verify.go
We want to only display the usage message if there is an error in the parsing of arguments. Once the arguments are parsed and we invoke the internal implementation the usage message should not be displayed anymore, regardless of what internal error gets returned. Fortunately, the fix is easy.
Tested:
* passing scenario:
```
[...]$ slsa-verifier verify-artifact \
--provenance-path multiple.intoto.jsonl \
--source-uri github.com/example/repo fib
Verified signature against tlog entry index 9712459 at URL: ...
Verified build using builder ...
Verifying artifact fib: PASSED
PASSED: Verified SLSA provenance
```
* failing scenario with missing artifact file:
```
[...]$ slsa-verifier verify-artifact \
--provenance-path multiple.intoto.jsonl \
--source-uri github.com/example/repo fibs
Verifying …
```
=> fix: Use `Run` instead of `RunE` to handle usage/errors

cli/slsa-verifier/verify.go
Fixes e2e tests, for e.g. https://github.com/slsa-framework/slsa-github-generator/issues/1445
The error showed that the exit code for failing verification was 0. This was a small regression from PR https://github.com/slsa-framework/slsa-verifier/pull/424 that changed RunE to Run, and so the exit status was removed.
=> fix: fix exit status on command execution errors

.github/workflows/release.yml
> args
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: fix a deprecation warning

cli/slsa-verifier/main_regression_test.go
Fixes https://github.com/slsa-framework/slsa-verifier/issues/440
This adds back in the commented out tests for testing the short form of the builder ID for GHA artifacts and images `builder@TAG`. The tests were failing because they set `allowRef = false`, but for GHA, the builder identity returned is always in long form, meaning that we have to allow the short form matches in the test (which is also done in the code path: https://github.com/slsa-framework/slsa-verifier/blob/5eea7c55379c777df48a3e5a95cedea44169f6c1/verifiers/internal/gha/builder.go#L105)
cc @laurentsimon
=> test: add builder id tests for short form

verifiers/internal/gcb/provenance.go, verifiers/internal/gha/provenance.go, verifiers/internal/gha/provenance_test.go
closes https://github.com/slsa-framework/slsa-verifier/issues/492
=> feat: verify sourceURI for npm packages

.github/workflows/scripts/pre-release/references.sh, README.md, RELEASE.md, actions/installer/README.md
closes https://github.com/slsa-framework/slsa-verifier/issues/522
=> docs: update installation to cover the Action and to receive updates

.github/workflows/pre-submit.actions.yml, .github/workflows/pre-submit.references.yml
Fix printing an error in references check. Previously the echoed string was enclosed in double quotes and had backticks which are evaluated as a command. This change changes the string to use single quotes which are printed statically.
Also moves the references check to its own file that triggers when the PR description is updated. This allows for fixing the PR description after failures, and triggering the check to re-run.
/cc @asraa
=> fix: Update references check

.github/workflows/pre-submit.actions.yml, README.md, RELEASE.md, SHA256SUM.md, actions/installer/README.md
=> chore: update docs for release v2.1.0

cli/slsa-verifier/verify/options.go
closes https://github.com/slsa-framework/slsa-verifier/issues/513
If people complain about the version, we can re-visit. If we make these optional, it will be impossible to remove.
=> feat: npm: Make package name and version mandatory for verification

verifiers/internal/gha/builder.go, verifiers/internal/gha/verifier.go, verifiers/utils/builder.go
Use the low-permissions delegator introduced in https://github.com/slsa-framework/slsa-github-generator/pull/2075 for the Node.js builder.
=> feat: Use low-perms delegator for Node.js builder

.github/workflows/pre-submit.lint.yml, .golangci.yml, verifiers/internal/gha/builder.go, verifiers/internal/gha/builder_test.go, verifiers/internal/gha/provenance.go, verifiers/internal/gha/verifier.go, verifiers/utils/structures.go
closes https://github.com/slsa-framework/slsa-verifier/issues/601
CLI e2e tests will be tacked as part of https://github.com/slsa-framework/slsa-verifier/issues/603
=> feat: BYOB verification support

errors/errors.go, verifiers/internal/gha/builder.go, verifiers/internal/gha/provenance_forgeable.go, verifiers/internal/gha/provenance_forgeable_test.go, verifiers/internal/gha/provenance_test.go, verifiers/internal/gha/slsaprovenance/v1.0/provenance.go
closes https://github.com/slsa-framework/slsa-verifier/issues/611
=> feat: Use env variable to retrieve trigger workflow

verifiers/internal/gha/provenance_test.go, verifiers/internal/gha/slsaprovenance/v1.0/provenance.go
Reverts the logic in https://github.com/slsa-framework/slsa-verifier/commit/db0560e3285e082f58a6d718a720047bb302fdd9.
For now, we assume a GHA builder verifier contract to detect the source in the first resolvedDependency. Per SLSA discussions, we will likely resolve this with some metadata in the name or annotations to distinguish the dependencies.
* fix: Use the first resolvedDependencies for SLSA v1.0 source verification
=> fix: revert to using resolvedDepdendencies for source verification

errors/errors.go, verifiers/internal/gha/provenance.go, verifiers/internal/gha/provenance_test.go
closes https://github.com/slsa-framework/slsa-verifier/issues/630
=> fix: only allow hashes of 256 bits or more

README.md, cli/slsa-verifier/main_regression_test.go, verifiers/internal/gha/verifier.go
* Removes the experimental guard around Sigstore bundle / SLSA v1.0 usage.
Experimental is still required for npm verification, but this enables the container-based builder.
=> feat: remove experimental on Sigstore bundle and v1.0 SLSA provenance format

.github/workflows/pre-submit.cli.yml, .github/workflows/pre-submit.e2e.yml, .github/workflows/pre-submit.lint.yml, .github/workflows/release.yml, .golangci.yml, go.mod
=> refactor: Use Go 1.20

.github/workflows/scripts/e2e-cli.sh
=> fix: pre-submit: e2e-cli.sh artifact download

verifiers/internal/gha/provenance.go, verifiers/internal/gha/provenance_test.go, verifiers/utils/git.go, verifiers/utils/git_test.go
Adds the functions `NormalizeGitURI`, `ParseGitURIAndRef`, and `ValidateGitRef`. `ParseGitRef` was updated to be permissive of the ref type whereas `ValidateGitRef` validates that the type is of a given type.
Code extracted from #641
=> refactor: Add more git utils

.github/workflows/pr-title.yml, verifiers/internal/gha/provenance.go, verifiers/internal/gha/verifier.go
closes https://github.com/slsa-framework/slsa-verifier/issues/672
=> feat: Print byob builder

README.md
Add installation using Homebrew on macOS
=> feat: Add homebrew formula to README

SECURITY.md
Propose a security policy (largely [borrowed](https://github.com/theupdateframework/go-tuf/blob/35c71e42cd12aeac00b6e323f7748f2daac90c59/docs/SECURITY.md) from go-tuf) that users should consult in order to report any security vulnerability.
Note that privately reporting security vulnerabilities requires turning on a GitHub [setting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository).
=> docs: Propose a security policy

renovate.json
Makes renovate create PRs for dependency updates monthly rather than weekly.
https://docs.renovatebot.com/presets-schedule/#schedulemonthly
Also sets vulnerability PRs to be scheduled daily.
https://docs.renovatebot.com/configuration-options/#vulnerabilityalerts
=> ci: Make renovate schedule monthly

renovate.json
Should fix https://github.com/slsa-framework/slsa-verifier/issues/726
=> chore: Fix renovate.json

README.md, verifiers/internal/gha/verifier.go
triggered on specification of COSIGN_REPOSITORY env
=> feat: Add cosign registry opts for provenance registry

verifiers/internal/gcb/provenance.go
Previously we used the go-cmp's Diff for displaying a human-friendly diff between two structs in an error message.
I had intended to do a json print of the structs and do a line-by-line diff. There is an internal library for calculating text diff, but I don't see any external functions that expose it to make it available for our use: https://pkg.go.dev/golang.org/x/tools/internal/diff
Instead, this we will simply display both structs in their own "actual" and "expected" sections. The user can use their other tools to find a human-friendly diff.
=> fix: #642: don't use go-cmp for outputting diff

README.md, SHA256SUM.md, actions/installer/README.md
This sets the expected sha256 of the v2.5.1 slsa-verifier released binary.
How to LGTM this PR (I'll work on a proper doc for this in https://github.com/slsa-framework/slsa-github-generator/issues/112):
1. Download the binary and provenance from https://github.com/slsa-framework/slsa-verifier/releases/tag/v0.0.1
2. Clone the slsa-verifier repo, compile and verify the provenance using the steps described in https://github.com/slsa-framework/slsa-verifier/blob/main/RELEASE.md#verify-provenance
```
$ bash verify-release.sh v2.5.1
```
The output hash should be the hash I'm updating to in this PR. If they match, LGTM. If they don't, someone tampered with the released binary and don't LGTM
=> chore: Update doc and digests for v2.5.1

.github/workflows/post-commit.yml, .github/workflows/update-actions-dist-post-commit.yml, docs/CONTRIBUTING.md
Add a new Post-Commit workflow, to make these renovate-bot updates a bit easier.
Previously, we had to clone the PR locally, run `make package`, and then push to the PR.
Now we would just need to use the github UI to invoke this new workflow against the PR number.
We could also copy this over to the slsa-github-generator repo.
> A workflow to run against renovate-bot's PRs,
> such as `make package` after it updates the package.json and package-lock.json files.
> The potentially untrusted code is first run inside a low-privilege Job, and the diff is uploaded as an artifact.
> Then a higher-privilege Job applies the diff and pushes the changes to the PR.
> It's important to only run this workflow against PRs from trusted sources, after also reviewing the changes!
Tested in my own private …
=> feat: workflow to update actions dist

.github/workflows/update-actions-dist-post-commit.yml
changing the update-dist workflow to use the `pr_number` input as an env variable to avoid [script injection](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#good-practices-for-mitigating-script-injection-attacks).
Our workflows are only invokable by our trusted maintainers so we should be okay. This is just an extra hardening measure.
Open issue https://github.com/actions/runner/issues/1070#issuecomment-2113287699
I confirmed the issue by invoking the workflow with `650 && echo SCRIPT INJECTION`, and it did also do the extra `echo` command.
- https://github.com/slsa-framework/slsa-verifier/actions/runs/9101350247/job/25018333703#step:3:36
after invoking the workflow again with this PR's version, the problem is mitigated.
- …
=> fix: use pr_number as env variable

.github/workflows/release.yml
The slsa-github-generator's workflow ref needs to be pinned by tag, not by hash.
Fixes this error
- https://github.com/slsa-framework/slsa-verifier/actions/runs/9893912259/job/27330429383#step:4:17
```
Verifying slsa-verifier-linux-arm64 using slsa-verifier-linux-arm64.intoto.jsonl
Verified signature against tlog entry index 110869188 at URL: https://rekor.sigstore.dev/api/v1/log/entries/24296fb24b8ad77aa9a66ae8969e055f85c9ec9e0ebbe52e4947cd33cf7b84af120088fe641b8e84
Verifying artifact slsa-verifier-linux-arm64: FAILED: invalid ref: "c747fe7769adf3656dc7d588b161cb614d7abfee": unexpected ref type: ""
FAILED: SLSA verification failed: invalid ref: "c747fe7769adf3656dc7d588b161cb614d7abfee": unexpected ref type: ""
```
=> fix: use tag for the builder in the release workflow

README.md, SHA256SUM.md, actions/installer/README.md
#label:release v2.6.0
Clone the repo and run the script described in https://github.com/slsa-framework/slsa-verifier/blob/main/RELEASE.md#verify-provenance. 
```
$ bash verify-release.sh v2.6.0
```
This will download the release files and verify the binaries. Confirm that the output hashes matches those in this PR's SHA256SUM.md
- https://github.com/slsa-framework/slsa-verifier/pull/789/files#diff-7834ca792905514302a0630d1c57dc1d330569a18fc2fff4aac6129efb00f4ccR1-R8
=> chore: v2.6.0: update docs

CODEOWNERS
This will assign teams rather than individuals to PRs.
=> chore: Update CODEOWNERS to use teams

.github/workflows/pre-submit.lint.yml, .golangci.yml, cli/slsa-verifier/main_regression_test.go, go.mod, verifiers/internal/gcb/provenance_test.go, verifiers/internal/gcb/slsaprovenance/v0.1/provenance_test.go, verifiers/internal/gcb/slsaprovenance/v1.0/provenance_test.go, verifiers/internal/gha/builder_test.go, verifiers/internal/gha/bundle_test.go, verifiers/internal/gha/npm_test.go, verifiers/internal/gha/provenance_forgeable_test.go, verifiers/internal/gha/provenance_test.go, verifiers/internal/gha/rekor_test.go, verifiers/internal/gha/slsaprovenance/slsaprovenance_test.go, verifiers/internal/vsa/verifier_test.go, verifiers/utils/builder_test.go, verifiers/utils/dsse_test.go
This PR updates go to 1.23.1 and updates golanci-lint to v1.61.1, while fixing new lint errors.
=> chore: update go and golanci lint

actions/installer/action.yml
This PR relates to the discussion from https://github.com/slsa-framework/slsa-verifier/issues/806 regarding the Node16 deprecation notice.
There are no changes to the `dist/` folder with the change to Node20 (used `v20.17.0`) - this is completely drop-in.
=> feat(action): Updating to Node20

README.md, SHA256SUM.md, actions/installer/README.md
#label:release v2.7.0
Updates docs to reference the new v2.7.0 release.
**How to verify**
Clone the repo and run the script described in https://github.com/slsa-framework/slsa-verifier/blob/main/RELEASE.md#verify-provenance. 
```
git clone git@github.com:slsa-framework/slsa-verifier.git
cd slsa-verifier
chmod +x verify-release.sh
GH_TOKEN=`gh auth token` bash verify-release.sh v2.7.0
```
Using the temp directory logged from the above command
```
cd <logged temp directory from running verify-release.sh>
sha256sum * | grep -v "intoto"      
36694b43ab23be234add09272e5faf77349d7e267bf65c01dc9bcdf58c4f496e  slsa-verifier-darwin-amd64
84d9122ce12e0c79080844285fd5c4976407ed3463e434a1b21b0979c46b1e55  slsa-verifier-darwin-arm64
499befb675efcca9001afe6e5156891b91e71f9c07ab120a8943979f85cc82e6 …
```
=> chore: Update docs for v2.7.0

cli/slsa-verifier/main_regression_test.go
Make the regression tests that do online access not run in parallel.
Besides VSA tests, all regression tests do some kind of online access of either TUF or Rekor.
=> fix: no parallel regression tests
