README.md, go.mod, main.go, pkg/provenance.go, pkg/provenance_test.go
Update package names and other references of the original repo.
=> ✨ Update package names and other references

README.md, main.go
Disable versioned tag until properly tested
=> ✨ Disable versioned tag

README.md
Add the Google blog post link.
@josepalafox let us know when you have the GitHub link, thanks!
=> ✨ Blog post link

main_test.go
=> ✨ Remove debug messages

README.md, main.go
See https://github.com/slsa-framework/slsa-github-generator-go/issues/47
=> ✨ Update name of `--binary` to `--artifact-path`

.github/workflows/pre-submit.yml, pkg/provenance.go
=> ✨ Add more details to errors

.github/workflows/release.yml
=> chore: bump release generator version

main_test.go
Turns out I had the wrong errors for the malicious tests -- I was relying on flakiness to PASS. :/
=> test: fix test error returns

pkg/provenance.go
* fix: Correctly resolved the sharded uuid returned by rekor.
Same as #140 except for main.
=> fix: properly handle sharded uuids returned from rekor

RELEASE.md
Signed-off-by: Ceridwen Driskill <cdriskill@google.com>
=> Releases url fix

README.md
To verify:
go run cli/slsa-verifier/main.go
go install github.com/slsa-framework/slsa-verifier/cli/slsa-verifier
=> Fix version in README

cli/slsa-verifier/main.go
=> Never panic, always return error

cli/slsa-verifier/main.go
closes https://github.com/slsa-framework/slsa-verifier/issues/203
Last issue to address https://github.com/slsa-framework/slsa-verifier/milestone/5
=> feat: make builder-id flag experimental until fully tested

cli/slsa-verifier/main.go
=> fix: use experimental flag value 1

.github/config-release.yml
=> ci: fix path to binary for release

.github/config-release.yml
=> fix: fix dir in release config

.github/workflows/release.yml, pkg/provenance.go
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/762
=> [backport v1.0] fix: fix intermediate certificate validaiton

README.md
closes https://github.com/slsa-framework/slsa-verifier/issues/237
=> Correct installation command in README

pkg/rekor.go
Similar to https://github.com/slsa-framework/slsa-verifier/pull/278/
for v1.2
=> fix(backport/v1.2): make client shard aware when verifying

verifiers/internal/gha/rekor.go
=> fix(backport/v1.3): make client shard aware when verifying

.github/workflows/release.yml
=> ci: update builder version for release/v1.1

.github/config-release.yml, .github/workflows/release.yml
=> fix: fix release configuration and workflow for version info

.github/workflows/release.yml
=> release/v1.3: update release builder

.github/workflows/release.yml
=> release/v1.2: update release builder

.github/workflows/release.yml
=> release/v1.1: update release builder

.github/workflows/codeql-analysis.yml, .github/workflows/pre-submit.cli.yml, .github/workflows/pre-submit.lint.yml, .github/workflows/release.yml, .github/workflows/scorecards.yml, .golangci.yml, .yamllint.yaml, Makefile, cli/slsa-verifier/main_test.go
=> Add golangci-lint and yamllint

renovate.json
Copy [slsa-github-generator's renovate config](https://github.com/slsa-framework/slsa-github-generator/blob/9b9fcaafa6389b9afb48e6d369e06f588adde7ba/renovate.json)
- Group updates to GitHub Actions
- Group go package updates to minor, patch versions.
- Group npm package updates to minor, patch (non-dev) dependencies.
- Group npm package updates to all devDependencies.
Signed-off-by: Ian Lewis <ianmlewis@gmail.com>
=> Update renovate config to group PRs

SHA256SUM.md
```console
$ sha256sum slsa-verifier-linux-amd64 
8d2e93a9ea0126d5daec22f2778b42fea79192605d16955f0c91847c3a6a8921  slsa-verifier-linux-amd64
```
Signed-off-by: Shunsuke Suzuki <suzuki.shunsuke.1989@gmail.com>
=> docs: add the checksum of v2.0.0

RELEASE.md
See title. Thanks to @suzuki-shunsuke for detecting this issue with new major versions
=> docs: add release steps for a new major release

.github/workflows/e2e.schedule.cli.yml
Signed-off-by: Ian Lewis <ianlewis@google.com>
=> ci: Use github.token to create issues

renovate.json
=> ci: add git sign off to renovate-bot

cli/slsa-verifier/verify.go
Fixes #425 introduces by #419
Signed-off-by: Mihai Maruseac <mihaimaruseac@google.com>
=> fix: Expect at least one artifact in verification

.github/workflows/pre-submit.lfs.yml
Add a large file size pre-submit check.
Signed-off-by: Ian Lewis <ianlewis@google.com>
=> ci: Add large file pre-submit check

renovate.json
Signed-off-by: Ian Lewis <ianlewis@google.com>
=> ci: Add go mod tidy to renovate post update

.slsa-goreleaser/windows-amd64.yml, .slsa-goreleaser/windows-arm64.yml
- https://github.com/slsa-framework/slsa-verifier/issues/526
=> chore: add a file extension ".exe" to Windows artifacts

.github/workflows/release.yml
Successful workflow: _https://github.com/developer-guy/slsa-verifier/actions/runs/4467186613_
=> feat: verification for provenance

README.md
Fix the badge image that is no longer loading properly. Also update the url to be more friendly to new users.
=> fix: Slack badge

experimental/maven-plugin/README.md, experimental/maven-plugin/pom.xml, experimental/maven-plugin/src/main/java/io/github/slsa-framework/SlsaVerificationMojo.java
Adds the maven plugin from https://github.com/slsa-framework/slsa-github-generator/pull/2439
=> feat: move maven-plugin from slsa-github-generator

CODEOWNERS
I'm not really contributing to slsa-verifier anymore.
=> chore: Remove ianlewis from CODEOWNERS

CODEOWNERS
=> feat: add ramonpetgrave64 as CODEOWNER

.github/workflows/pr-title.yml
Updates `thehanimo/pr-title-checker` to v1.4.2 and fixes the version comment.
=> chore: fix pr-title-checker
